name: "Nix stable packaging test"
on:
  pull_request:

jobs:
  Build-Package:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v27
      with:
        nix_path: nixpkgs=channel:nixos-24.11
    - run: nix build

